### ISSUE TITLE
package.json?

### ISSUE THREAD

**Issue by Jonathan50** [Newawe/newawe-node#10]
Should this be an npm package? Or not?

**Comment by bjskistad** [comment]
No, it's a website, not a package. XD

**Comment by Jonathan50** [comment]
Well, scratch-www has a package.json.
Also, there's a node_modules directory, which should not be here (it should be in the gitignore) and having a package.json makes it easy to install the dependencies.

**Comment by bjskistad** [comment]
Sure. Make one. XD

**Comment by Jonathan50** [comment]
Should I call it `newawe` or `newawe-node`?

**Comment by Jonathan50** [comment]
And version? I could just leave it 1.0.0 if it's not important.

**Comment by Jonathan50** [comment]
Author?

**Comment by bjskistad** [comment]
Newawe. Ver 1.0.0

**Comment by Jonathan50** [comment]
And the only dependency is `bcrypt-nodejs`? And the author and license?

**Comment by Jonathan50** [comment]
Is the author `Newawe` okay? And GPLv3?

**Comment by bjskistad** [comment]
Yeah.

**Comment by Jonathan50** [comment]
Done.

**Comment by Jonathan50** [comment]
Yay, it works! Now it's easy to install dependencies and run.

**Comment by bjskistad** [comment]
Awesome!
