### ISSUE TITLE
Register bug(s)

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe-node#103]
I just tried to submit an empty registration form and now I can not pick a country. The country selector is blue and I can't click it. Let me know if you need a screenshot.

**Comment by bjskistad** [comment]
Still a problem?

**Comment by bjskistad** [comment]
I did the same thing. Just reloading the page fixed it.

**Comment by HittmanA** [comment]
Ok thanks.

**Comment by HittmanA** [comment]
let me try

**Comment by HittmanA** [comment]
Didn't for me. I tried reloading the page and it 404'd me.

**Comment by bjskistad** [comment]
lol

**Comment by bjskistad** [comment]
'404'd'

**Comment by HittmanA** [comment]
yeah xD its what I call getting a 404 page.
