### ISSUE TITLE
Country field in "Registration"

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe-node#111]
The country field does not appear after you do not fill in all fields. I heard there was a PHP fie that could render the countries, but don't know how to implement

**Comment by bjskistad** [comment]
We're not using PHP. We would have to use htmlgetitembyid() I believe.

**Comment by joker314** [comment]
But are we using JS server-side? Could we then somehow add {{{countries}}} thingy, to make it replace that with the contents of another file? We could dump a variable or something?

**Comment by bjskistad** [comment]
I believe so, idk how to though.
