### ISSUE TITLE
?p=

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe-node#112]
I'm not sure I like the ?p= tag. Is there a way to get rid of it?

**Comment by herohamp** [comment]
Well we would have to reroute ALL the pages

**Comment by joker314** [comment]
Where? In the URL? Or in the HTML?

**Comment by herohamp** [comment]
URL i think

**Comment by joker314** [comment]
Thx

**Comment by joker314** [comment]
Would it be possible to use "virtual directories"  or whatever, like in Scratch, to mke it look like a directory, but it actually being an argument?

**Comment by herohamp** [comment]
yeah

**Comment by Radical-from-Scratch** [comment]
We should do that.

**Comment by joker314** [comment]
researching... (unless you know how to do it?)

**Comment by Radical-from-Scratch** [comment]
Um, younneed to modify .htaccess i wouldngive more detail but i am on my phone

**Comment by herohamp** [comment]
that is for apache not node

**Comment by joker314** [comment]
Is there a settings fie in node then?

**Comment by joker314** [comment]
*file

**Comment by herohamp** [comment]
no we must edit our server file to change the way we serve files

**Comment by joker314** [comment]
Ok. Does this help on how to change it?: http://stackoverflow.com/questions/10618418/how-can-i-implement-virtual-directories-with-node-js-and-express

**Comment by herohamp** [comment]
I am at school ATM so kinda not

**Comment by joker314** [comment]
Ok. I'll do some research for now.

**Comment by herohamp** [comment]
k

**Comment by as-com** [comment]
There is no such thing as htaccess when it comes to Node apps. The
application is the web server itself! (Although it is still best practice
to put something like nginx reverse proxy in front of it)

The feathers branch has this feature called *routing* which automatically
loads and renders the React component that matches the URL in the address
bar.

**Comment by herohamp** [comment]
I have a nodeJS proxy in frount of newawe ATM

**Comment by Radical-from-Scratch** [comment]
I know zero Node so I apologize if I am off.

**Comment by bjskistad** [comment]
lol same

**Comment by Radical-from-Scratch** [comment]
You too? It was your IDEA to use node!!!!!!!!

**Comment by Jonathan50** [comment]
You'd need to change some stuff in server.js. But in the feathers branch I don't believe there is ?p=.

**Comment by HittmanA** [comment]
I don't know any node

**Comment by herohamp** [comment]
We are using node because it is alot more stable and better than php

**Comment by Radical-from-Scratch** [comment]
Ironically, two-thirds of the website is PHP. You're welcome to help me out on the forums or the wiki.

**Comment by herohamp** [comment]
xD ok

**Comment by Jonathan50** [comment]
@Radical-from-Scratch no it isn't

**Comment by Radical-from-Scratch** [comment]
Yes it is. Except for the main site, it's *all* in PHP

**Comment by Jonathan50** [comment]
\*facepalm\* **NONE** of our code is PHP.

**Comment by Radical-from-Scratch** [comment]
Except for the main site, it is ALL in PHP.

**Comment by herohamp** [comment]
yes 2/3 the wiki and fourm. But I suggest we use a nodeJS fourm and wiki

**Comment by Jonathan50** [comment]
@Radical-from-Scratch None of our code is in PHP!

**Comment by herohamp** [comment]
https://github.com/Newawe/newawe-forums

**Comment by Radical-from-Scratch** [comment]
NodeBB is unreliable and there is (at this time) no such thing as a node wiki. 

Besides, I do not want to start all over.

**Comment by herohamp** [comment]
ok.

**Comment by Jonathan50** [comment]
I said "our code"

**Comment by Radical-from-Scratch** [comment]
Actually, we won't be just taking it right out of the box and slapping it on the website, so it is partially our code.

**Comment by Jonathan50** [comment]
Okay

**Comment by Jonathan50** [comment]
But \*this repository\* will have no PHP.

**Comment by herohamp** [comment]
Jonathan. This is the main site which we will embed the php fourm into

**Comment by Jonathan50** [comment]
I know that.

**Comment by herohamp** [comment]
sorry

**Comment by as-com** [comment]
@Radical-from-Scratch Please at least run a DuckDuckGo search: https://github.com/claudioc/jingo

**Comment by Radical-from-Scratch** [comment]
I did Google. Is that OK?

**Comment by masterex1000** [comment]
what is wrong with ?p=

**Comment by as-com** [comment]
@masterex1000 It's really ugly, and is also bad for SEO.

**Comment by herohamp** [comment]
hmm so we should make a /contact /signup /login pages?

**Comment by as-com** [comment]
I've already got the signup and login pages on the Feathers branch (non-functional for now, because I'm working on the backend part)

**Comment by herohamp** [comment]
ok

**Comment by Radical-from-Scratch** [comment]
I asked to remove it a while back and everyone was like "NO WAI!!!!!"

**Comment by masterex1000** [comment]
i can add part of the backend it is not that hard
