### ISSUE TITLE
Profile Pages

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe-node#115]
I was thinking of doing the profile pages (or rather - somebody suggested it to me) but I'm really confused. Here are the questions I have

* Do I use Node.js or PHP?
* How do I run some code server-side to make the site "dynamic"?

Thanks, not really an issue

**Comment by Mrcomputer1** [comment]
> Do I use Node.js or PHP?

Node.js - Newawe does not use PHP

> How do I run some code server-side to make the site "dynamic"?

IDK

**Comment by joker314** [comment]
thx

**Comment by bjskistad** [comment]
We can keep this open for future discussion about it.

**Comment by joker314** [comment]
K, but I opened a second issue simillar to this
