### ISSUE TITLE
Code Habits and Errors

### ISSUE THREAD

**Issue by RonSkons** [Newawe/newawe-node#122]
If you look at our codacy page ([https://www.codacy.com/app/ron852719/newawe/dashboard](https://www.codacy.com/app/ron852719/newawe/dashboard)), you will notice just how many errors we have. Maybe we should work to fix these?

**Comment by BKFighter** [comment]
I've never heard of codacy before! I'll try to work on that later tonight.

**Comment by RonSkons** [comment]
Great!

**Comment by bjskistad** [comment]
Awesome! Yeah, we'll work on it.
