### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe-node#123]
So what are we using to host the website? HG? GoDaddy? 

I got a professional recommendation to use [Site5](https://www.site5.com/), shold we use that?

**Comment by RonSkons** [comment]
How about [AWS EC2](https://aws.amazon.com/ec2/pricing/)? There is a one-year free trial, and its pretty cheap afterwards. That means we can host free for one year, and if the project is still alive *crosses fingers* we can buy more time.

**Comment by RonSkons** [comment]
Or Gwiddle...?
Anyone have anything against gwiddle?

**Comment by herohamp** [comment]
Yes!

**Comment by RonSkons** [comment]
What?

**Comment by herohamp** [comment]
http://blog.herohamp.xyz then click on gwiddle

**Comment by RonSkons** [comment]
Oh. Thats too bad. What do you think of AWS? I once hosted my minecraft server on there :P

**Comment by herohamp** [comment]
👍🏻

**Comment by herohamp** [comment]
AWS is good!

**Comment by RonSkons** [comment]
Cool. Anyone have an account? I forgot mine.

**Comment by herohamp** [comment]
we should use @barans as e is the owner!

**Comment by barans** [comment]
what? :D

**Comment by RonSkons** [comment]
Did we just mention the wrong person?

**Comment by herohamp** [comment]
Yup

**Comment by barans** [comment]
no problem have fun guys :)

**Comment by herohamp** [comment]
Sorry @barans
Damn it that was the second one today. Dang you phone

**Comment by RonSkons** [comment]
Lol sorry @barans. Meant to mention @bjskistad.

**Comment by barans** [comment]
use digitalocean or linode in my opinion

**Comment by herohamp** [comment]
Thanks!

**Comment by as-com** [comment]
I wouldn't recommend AWS \- it can get pretty expensive, and the cheapest tier
does not give you much. For example, you might end up paying lots for
bandwidth and disk
I/O.![](https://link.nylas.com/open/f0mfv9rl15jj0eu3sdoetwx6v/local-
1ef42969-969b?r=cmVwbHkrMDAzYTQ4NjkwMGYyMGYyZWVlYzQ2OGQ0ZTk2NzE3MmM5OTUxNTJhZjRkZGM3MWNmOTJjZjAwMDAwMDAxMTM3ZWFhODY5MmExNjljZTA5OTljNDhhQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 19 2016, at 2:46 pm, Ron Friedman &lt;notifications@github.com&gt;
wrote:  

> Lol sorry
[@barans](https://github.com/barans&r=cmVwbHkrMDAzYTQ4NjkwMGYyMGYyZWVlYzQ2OGQ0ZTk2NzE3MmM5OTUxNTJhZjRkZGM3MWNmOTJjZjAwMDAwMDAxMTM3ZWFhODY5MmExNjljZTA5OTljNDhhQHJlcGx5LmdpdGh1Yi5jb20=).
Meant to mention
[@bjskistad](https://github.com/bjskistad&r=cmVwbHkrMDAzYTQ4NjkwMGYyMGYyZWVlYzQ2OGQ0ZTk2NzE3MmM5OTUxNTJhZjRkZGM3MWNmOTJjZjAwMDAwMDAxMTM3ZWFhODY5MmExNjljZTA5OTljNDhhQHJlcGx5LmdpdGh1Yi5jb20=).

>

> —  
> You are receiving this because you are subscribed to this thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/Newawe/newawe/issues/123#issuecomment-227013478&r=cmVwbHkrMDAzYTQ4NjkwMGYyMGYyZWVlYzQ2OGQ0ZTk2NzE3MmM5OTUxNTJhZjRkZGM3MWNmOTJjZjAwMDAwMDAxMTM3ZWFhODY5MmExNjljZTA5OTljNDhhQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/ADpIaWQPWtfaGYIv-z9EtN-
Dn4yPP4fkks5qNY6GgaJpZM4I5KXP&r=cmVwbHkrMDAzYTQ4NjkwMGYyMGYyZWVlYzQ2OGQ0ZTk2NzE3MmM5OTUxNTJhZjRkZGM3MWNmOTJjZjAwMDAwMDAxMTM3ZWFhODY5MmExNjljZTA5OTljNDhhQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/ADpIae-O19kerJolkOa5Qgmm0hpK46NZks5qNY6GgaJpZM4I5KXP.gif)

**Comment by RonSkons** [comment]
Ok. BTW your comment has a bunch of weird formatting issues.

**Comment by herohamp** [comment]
Yeah

**Comment by Radical-from-Scratch** [comment]
The original plan was to use HG, but people have other ideas. I'll make a poll later today and post the link.

**Comment by Radical-from-Scratch** [comment]
Here is the poll: https://www.surveymonkey.com/r/X6LJ9NR I said I was doing it all myself, but only the verification did I actually end up doing myself :P

**Comment by bjskistad** [comment]
Took the survey.
