### ISSUE TITLE
One Bug fixed! Now Another!

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe-node#15]
After Iclys fix I got 
```
return substitute(readFile("assets/global.html"),{"content": substitute(readFile("assets/pages/" + config.pages[pageName].file), {"page-title": config.pages[pageName].title, "site-title": config.pages[pageName].siteTitle})});
	                                                                                                                         ^

TypeError: Cannot read property 'file' of undefined
    at globalSiteText (/Users/hamptonmoore/Documents/Github/newawe-node/server.js:61:123)
    at Server.<anonymous> (/Users/hamptonmoore/Documents/Github/newawe-node/server.js:245:19)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by Jonathan50** [comment]
https://github.com/Newawe/newawe-node/blob/master/server.js#L61

**Comment by Jonathan50** [comment]
It wasn't caused by @Icelys fix, fwiw

**Comment by Jonathan50** [comment]
It's because the page `pageName` doesn't exist in config.json.

**Comment by Icelys** [comment]
Should we add error catching, and return a backend error? For that func

**Comment by Jonathan50** [comment]
look for all the places `globalSiteText` is called and make sure that the page it is called with exists.

**Comment by Jonathan50** [comment]
It happens here: https://github.com/Newawe/newawe-node/blob/master/server.js#L192

`config.index` is not a page!!!

**Comment by Icelys** [comment]
I mean in the file def

**Comment by Jonathan50** [comment]
Okay it happens here:
https://github.com/Newawe/newawe-node/blob/master/server.js#L245
And it would happen the other places the page 'config.index' is being rendered in that same function.

**Comment by Jonathan50** [comment]
@Icelys I don't know what you're talking about.

**Comment by Jonathan50** [comment]
@Icelys What is `config.index`?

**Comment by Icelys** [comment]
I think it should be called not as a string. So [config.index]

**Comment by Jonathan50** [comment]
Oh, your right. config.index is `"home"` in config.json. What's up with the brackets you wrote though?

**Comment by Icelys** [comment]
I'm on mobile.

**Comment by Jonathan50** [comment]
d4c0bf6f065ab23779a9f60568e23228744a47ee Done!

**Comment by Jonathan50** [comment]
Woah, if you name a commit `Fix #number` GitHub automatically closes issue #number? That's cool.
