### ISSUE TITLE
Find a better way to use the {{ something }}

### ISSUE THREAD

**Issue by adri326** [Newawe/newawe-node#4]
As I saw, you just replace and replace again the many {{ something }} tags you find, but I don't think it's really a good idea to put it in one line: it will make it hard to modify and as I saw, you copied the replaces, and it'll make it hard to modify it because we'll have to modify each copy of the replaces methods. I think using some classes, functions and a .json could be a better way to use the {{ something }} tags.

**Comment by Icelys** [comment]
With this idea, I implemented this in my latest PR. Here is how I used it. 
```
contentReplace("This is content: {{ content }}, and title: {{ title }}", {"content": page.content, "title":"example"})
```
Is this what you had in mind?

**Comment by Jonathan50** [comment]
@Icelys Maybe make it more general?
```
substitute("This is content: {{ content }}, and title: {{ title }}", {"content": page.content, "title":"example"})
```

**Comment by Icelys** [comment]
That would make more sense. I'll change it.

**Comment by bjskistad** [comment]
Issue closed?

**Comment by adri326** [comment]
I close it

**Comment by bjskistad** [comment]
M'kay.
