### ISSUE TITLE
We need to make translations

### ISSUE THREAD

**Issue by DrKat123** [Newawe/newawe-node#48]
(Btw i assigned myself because i'll be in charge of translating this site to Indonesian)
Yeah, as the title says we need to make translations

**Comment by joker314** [comment]
I agree. We should have a language bar at the bottom of the page, like Scratch does.

**Comment by joker314** [comment]
We should create a 2D array with all the words, like so:
`[ ["Hello", "Please Log In", "Do you have an account?", "Welcome back {{{user}}} how are you?"], ["Hola", "Log In Por Favor", "Tiene un account", "Bienvenidos {{{user}}} que tal?"] ]`
I made up some of the Spanish words, but I think this method would be good, since you would just do:
`response.write(text[langoption][3])`
What do you think for this method?

**Comment by DrKat123** [comment]
Yeah, that might work

**Comment by DrKat123** [comment]
Indonesian Translations:

Nama Pengguna|Username
Kata Sandi|Password
Daftar|Register

Etc

**Comment by joker314** [comment]
I added a JSON file with my russian translations, it is called languages.json and contains my russian translations. Perhaps you could add those in under a new, Indonesian, thingy (I'm not sure what it is called, I'm not good at JSON, only JS). So yeah.

**Comment by DrKat123** [comment]
Okay, i'll check it

**Comment by DrKat123** [comment]
I'll edit the JSON tomorrow
In an Android phone

**Comment by joker314** [comment]
Ok

**Comment by DrKat123** [comment]
and btw this is a correct JSON file:
```JSON
{
    "Russian": ["items here"],
    "Pig Latin": ["..."]
}```

**Comment by joker314** [comment]
So no `var x= {}`
Then I will get rid of that.

**Comment by DrKat123** [comment]
Yeah

**Comment by joker314** [comment]
Ok, that is done. This is pretty important, because the website structure needs to be changed

**Comment by DrKat123** [comment]
Yeah

**Comment by Radical-from-Scratch** [comment]
Oh hmm, I was thinking something like this.
'about' = "About Newawe"
'forums' = "Newawe Forums"
'createintro' = "Welcome to the  create page! Here, your dreams come true.

**Comment by joker314** [comment]
I don't get it

**Comment by Radical-from-Scratch** [comment]
What do you mean you don't get it? It's pretty similar to the one you posted as it self-explanitory.

**Comment by joker314** [comment]
Oh, I think I get it

**Comment by DrKat123** [comment]
Hopefully i can use the PC today

**Comment by herohamp** [comment]
https://translate.google.com/manager/website/

???

**Comment by bjskistad** [comment]
Lol

**Comment by herohamp** [comment]
I mean look at my website http://www.herohamp.xyz/

It can translate to almost any lang. I just need to fix the pos

**Comment by bjskistad** [comment]
We need to restyle that menu though. XD

**Comment by DrKat123** [comment]
Please no Google Translate
The translations is inaccurate

**Comment by joker314** [comment]
I agree, I tried it on yours and it was grammatically off (while meaning was preserved). We need manual translation.

**Comment by DrKat123** [comment]
Yeah

**Comment by herohamp** [comment]
Welp ok. I will contact my japanese friends

**Comment by DrKat123** [comment]
'Kay

**Comment by joker314** [comment]
Sorry for inactivity, is this stuff still active?

**Comment by joker314** [comment]
Um, the phrases need to be longer for languages like Russian. They need to be the whole sentence because the endings will change according to stuff around it

**Comment by JordanB-1337** [comment]
Dunno if you noticed, but we're using PHP now. This repo is now depracated.
