### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe-node#49]
Is there a way we can make the server startup again if i crashes?

**Comment by bjskistad** [comment]
Wouldn't you just start and stop it?

**Comment by herohamp** [comment]
Yes but sometimes I am at school or sleeping.

**Comment by joker314** [comment]
Perhaps if a developer merges a line of code something like:
`/*  Reboot at 1415on16042016 */`
and a program could read it and switch the server on and off, and then sleeps 2 mins (so that it doesn't continue rebooting until 60 secs are up).

**Comment by herohamp** [comment]
Is there a way with bash we can detect a shut down of the server then boot it backup?

**Comment by joker314** [comment]
Doing research now, but for now, if a dev discovers the server is bad, and they place the comment shown above, then doesn't the server automaticallu update every 15 mins. And when it does that, couldn't it check a certain line number and see if it matches the syntax /* Reboot at ... */ and then couldn't it somehow check the time and see whether that is within 15 mins of the thing or something? 
Perhaps this will help with that http://stackoverflow.com/questions/10929453/bash-scripting-read-file-line-by-line but you could also try pinging the server? (or telnet, or something that allows you to listen on a particular port).

Summary: Not sure.

**Comment by Jonathan50** [comment]
Just fix the bug.

What was in the log, @herohamp? It seemed to crash after I registered an account.

**Comment by Jonathan50** [comment]
> Is there a way with bash we can detect a shut down of the server then boot it backup?

Using `cron` may be better.

**Comment by herohamp** [comment]
Nuuu bash FTW

**Comment by DrKat123** [comment]
IIRC Cron is bash

**Comment by Mrcomputer1** [comment]
You could use [forever.js](https://www.npmjs.com/package/forever) to start the script when the script stops running

**Comment by DrKat123** [comment]
Good idea

**Comment by scratchyone** [comment]
Don't use forever.js! Sometimes it force the script to keep running when it
needs to restart to work. Just use a basic
```

while true; do

npm run start

done

```

On Tue, Apr 19, 2016 at 5:52 AM, Alexander Liu <notifications@github.com>
wrote:

> Good idea
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Newawe/newawe/issues/49#issuecomment-211728309>
>



--

**Comment by DrKat123** [comment]
okay

**Comment by Mrcomputer1** [comment]
Okay. I could not test forever.js because it keep giving me ETIMEOUT when trying to install it.

**Comment by Jonathan50** [comment]
Cron pls.

**Comment by Jonathan50** [comment]
@Mrcomputer1 you have an ancient NPM version, probably. Run
```
npm install -g npm
```

**Comment by DrKat123** [comment]
> IIRC Cron is Bash

**Comment by Jonathan50** [comment]
...

cron has *nothing* to do with bash

**Comment by DrKat123** [comment]
But i though i can use it on a bash terminal

**Comment by DrKat123** [comment]
And besides i put "IIRC"

**Comment by Jonathan50** [comment]
@DrKat123 
> But i though i can use it on a bash terminal

I don't understand...?

**Comment by Mrcomputer1** [comment]
@Jonathan50 
I don't have an ancient NPM version
> C:\Users\(Private)>npm --version
> 3.8.3

That is only 3 versions outdated (latest is 3.8.6)

Anyway I updated to 3.8.6 and got that same error
If you want to see the error: https://gist.github.com/Mrcomputer1/f3887694266cde8edfea761a2df02a3e

**Comment by DrKat123** [comment]
*.0.3 versions outated :P

**Comment by Icelys** [comment]
What I do for my nose scripts is I put the node command into a bash while loop, with a sleep 1 in between restarts so you can press control c twice to end it. Sorry for my bad description, I'm on mobile

**Comment by DrKat123** [comment]
Edited your tyop

**Comment by bjskistad** [comment]
And edited Alex's typo. XD

**Comment by DrKat123** [comment]
that tyop was intended

**Comment by bjskistad** [comment]
Lol
