### ISSUE TITLE
404 Not Working

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe-node#6]
Is the 404 file supposed to work? When I purposely try a 404, I don't get our 404 page. :(

**Comment by Icelys** [comment]
While working on my latest PR, I noticed a problem with the 404 page. I fixed it with my update in the PR. The issue was this (or probably): 
```
config.pages[config["404"]].file
```
 Instead of 
```
config.pages["404"].file
```
Most likely the error.

**Comment by bjskistad** [comment]
M'kay. I'll probably add your PR now... XD
