### ISSUE TITLE
404

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe-node#95]
Try registering an account on Newawe, with a username of XSS<>Test
This will contain invalid chars, and should give an error page, but instead gives a 404. I tried checking the config.json, but that seems fine. Is the return value wrong in server.js, or did I make a mistake in the config? This is probably due, to mme, as I've been adding stuff to the registration script of server.js.

tl;dr: 404 at a XSS attempt sign up

**Comment by DrKat123** [comment]
Lemme test this...

**Comment by joker314** [comment]
What are your results
P. S. I just crashed the site, sorry about that. I submitted an empty

**Comment by bjskistad** [comment]
Ok

**Comment by DrKat123** [comment]
error 404
