### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe-node#96]
How do we plan to do translation? I found a cool icon for it. http://emojione.com/wp-content/uploads/assets/emojis/1f310.svg

Also what langs will we support?

**Comment by Jonathan50** [comment]
:globe_with_meridians:

**Comment by herohamp** [comment]
http://emojione.com/licensing/

**Comment by herohamp** [comment]
`Our emoji graphics are free to use for any project, commercial or personal, under a free culture Creative Commons License (CC-BY 4.0). Proper attribution (link back) is required for the rights to use our emoji in commercial projects. View our attribution guide for details.` EmojiOne

**Comment by Jonathan50** [comment]
okay

**Comment by herohamp** [comment]
How do you show images in github?

**Comment by Jonathan50** [comment]
```md
![alternative text (optional)](http://url.com)
```

![](http://emojione.com/wp-content/uploads/assets/emojis/1f310.svg)

**Comment by joker314** [comment]
Native speakers should be translating in language.json. Every output should slowly be converted to an index in the json.

We could make our own language button (we'd be original)? Maybe make it multi-coloured?

**Comment by joker314** [comment]
We already have an issue for this btw.
"We need to make translations"

**Comment by herohamp** [comment]
Hmm I will do that after I am done eating. Should I model it off of the EmojiOne I sent?

**Comment by joker314** [comment]
Yes, since it is universally understood. Try to keep it as close as possible to its shape, but go wild with the colour scheme, and try to make it from scratch (lowercase scratch, not mit media lab stuff) Have a nice meal.

**Comment by herohamp** [comment]
Thx salmon is sooo good

**Comment by herohamp** [comment]
![](http://i.imgur.com/wFLomlb.png)

**Comment by herohamp** [comment]
![](http://i.imgur.com/faAL51N.png)

**Comment by herohamp** [comment]
Everyone Vote! 1 or 2!

**Comment by joker314** [comment]
I like it (the image). How is the salmon cooked?

**Comment by joker314** [comment]
1

**Comment by herohamp** [comment]
It is blacked

**Comment by scratchyone** [comment]
2

On Wednesday, April 20, 2016, Hampton <notifications@github.com> wrote:

> It is blacked
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Newawe/newawe/issues/96#issuecomment-212624113>
>


--

**Comment by joker314** [comment]
Oooh, blacked salmon, I'm jealous (but I'm also a bit sleepy).
Night.

**Comment by Jonathan50** [comment]
1

**Comment by 109C** [comment]
Plz explain.

**Comment by herohamp** [comment]
Explain what?

**Comment by bjskistad** [comment]
@109C We're voting for images.

**Comment by herohamp** [comment]
Baran, What do you want?

**Comment by 109C** [comment]
@herohamp How is the salmon cooked black?

**Comment by herohamp** [comment]
I don't know my mom made it.

**Comment by bjskistad** [comment]
I kinda like the original. :P But out of the two, I like the first.

**Comment by 109C** [comment]
I prefer the original too, the gradients look.. meh.

**Comment by herohamp** [comment]
So original?

**Comment by 109C** [comment]
Yup.

**Comment by bjskistad** [comment]
Yeah...

**Comment by herohamp** [comment]
ok

**Comment by 109C** [comment]
So github issues is the new IRC?

**Comment by herohamp** [comment]
yup

**Comment by herohamp** [comment]
Baran check gitter.im

**Comment by bjskistad** [comment]
kk

**Comment by Radical-from-Scratch** [comment]
I like 1

**Comment by DrKat123** [comment]
1

**Comment by herohamp** [comment]
I am confused? 1 or original?

**Comment by joker314** [comment]
Everybody, make a vote, 0, 1, or 2 (0-Original), only vote once, and lets see which is better? Unless bjskistad is in charge and xis word is final?

My Vote: 1

**Comment by Radical-from-Scratch** [comment]
I like 0 to be honest.

**Comment by bjskistad** [comment]
Me too... I don't want to be extreme overlord over this, just over the main logo. XD

**Comment by joker314** [comment]
Okay then, 0 it is. In which case, do we need attribution (their website says that non-commercial uses do not require attribution), so are we going to be profiting?

**Comment by Jonathan50** [comment]
It's CC-BY, so give attribution whether we're commercial or not.

**Comment by DrKat123** [comment]
1 for one
Not the original
:P

**Comment by HittmanA** [comment]
I vote for #1
