### ISSUE TITLE
I can't do anything until I have an answer.

### ISSUE THREAD

**Issue by Radical-from-Scratch** [Newawe/newawe-node#97]
What is the database query for checking someone's password? b-crypt

**Comment by joker314** [comment]
`var dataFile = "data.json"` This is already in server.js
`data = JSON.parse(readFile(dataFile));` This is already in server.js
And here is what you do after initialization:
`data["password"]` This returns the hashed password

**Comment by Radical-from-Scratch** [comment]
But what I will be accessing it from will not be written in node. Plus, why aren't we using MySQL?

**Comment by joker314** [comment]
Um, I dunno why we aren't using it. What language will you be writing the code in?

**Comment by Radical-from-Scratch** [comment]
PHP and PHP

**Comment by joker314** [comment]
`$path = fopen("data.json", "r");`
`$out = fread($path);`
`$data = json_decode($out);`
and now
`$data[$username]["password"];`
I think that might work? (Not sure)

**Comment by Radical-from-Scratch** [comment]
.....but "data.json", how will that be readable externally?

**Comment by bjskistad** [comment]
Hmm....

**Comment by joker314** [comment]
We can't make it public, so tell me more. Are yuo working on an external website, or the wiki, or...?

**Comment by Radical-from-Scratch** [comment]
I'm working on the forums and the wiki. The wiki will be on a subdomain and the forums will be on a subdirectory

**Comment by DrKat123** [comment]
I have an idea...
Idk if ir will work tho...

**Comment by joker314** [comment]
We could create a page that provides data of a user, and reporting it back. Alternatively, we could make all user data as a page (published)

**Comment by Radical-from-Scratch** [comment]
We are not creating a page that gives the hashed password.

**Comment by joker314** [comment]
Then could we mae a page that requires a password to provide everybody's hashed passwords?

**Comment by Radical-from-Scratch** [comment]
The fotum software is open source.

**Comment by HittmanA** [comment]
How often does the newawe website get the new data from GitHub?

**Comment by bjskistad** [comment]
Every 15 mins.

**Comment by Radical-from-Scratch** [comment]
But that is unrelated. That is not its permanet location.

**Comment by herohamp** [comment]
It does not update every 15mins. I can't figure out how with node :( it updated when I have time or told to. Now if somebody could write me a bash script to do that I would use it.

**Comment by HittmanA** [comment]
Could you have it update again? I added some new stuff.

**Comment by herohamp** [comment]
I will update it when I wake up. I do not have access to my computer ATM.



wow a wole post on my phone wihout typos!

**Comment by HittmanA** [comment]
Made one xD its whole not wole. Thanks for the info BTW.

**Comment by Radical-from-Scratch** [comment]
You made TWO typos.

**Comment by HittmanA** [comment]
@herohamp Update the website again please. I just added more rounded text boxes.

**Comment by HittmanA** [comment]
@herohamp Could you update newawe again? I made some changes.

**Comment by Radical-from-Scratch** [comment]
I thought it updated every 15 minutes

**Comment by herohamp** [comment]
no it does not. I need somebody to write a bash code that stops the server downloads the files then starts the server!

**Comment by Radical-from-Scratch** [comment]
Here's some bash code for you:

`
echo Nah, I'm too lazy
exit
`

**Comment by herohamp** [comment]
xD. I have tried but can't figure out how :(
